# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/gui_7_15_21.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1309, 806)
        MainWindow.setMinimumSize(QtCore.QSize(1309, 30))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.video_player = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_player.sizePolicy().hasHeightForWidth())
        self.video_player.setSizePolicy(sizePolicy)
        self.video_player.setMinimumSize(QtCore.QSize(854, 480))
        self.video_player.setMaximumSize(QtCore.QSize(1920, 1080))
        self.video_player.setStyleSheet("")
        self.video_player.setText("")
        self.video_player.setAlignment(QtCore.Qt.AlignCenter)
        self.video_player.setObjectName("video_player")
        self.verticalLayout_6.addWidget(self.video_player)
        self.video_slider = QtWidgets.QSlider(self.centralwidget)
        self.video_slider.setMinimumSize(QtCore.QSize(854, 20))
        self.video_slider.setMaximumSize(QtCore.QSize(1920, 16777215))
        self.video_slider.setOrientation(QtCore.Qt.Horizontal)
        self.video_slider.setObjectName("video_slider")
        self.verticalLayout_6.addWidget(self.video_slider)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.play_button.setFont(font)
        self.play_button.setObjectName("play_button")
        self.horizontalLayout_13.addWidget(self.play_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.stop_button.setFont(font)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_13.addWidget(self.stop_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem2)
        self.frame_viewer = QtWidgets.QLabel(self.centralwidget)
        self.frame_viewer.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_viewer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_viewer.setStyleSheet("")
        self.frame_viewer.setText("")
        self.frame_viewer.setObjectName("frame_viewer")
        self.verticalLayout_6.addWidget(self.frame_viewer)
        self.gridLayout.addLayout(self.verticalLayout_6, 2, 2, 4, 1)
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.open_button.setFont(font)
        self.open_button.setObjectName("open_button")
        self.gridLayout.addWidget(self.open_button, 6, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(17, 342, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.export_button.setFont(font)
        self.export_button.setObjectName("export_button")
        self.gridLayout.addWidget(self.export_button, 6, 5, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hue_Label = QtWidgets.QLabel(self.groupBox_2)
        self.hue_Label.setMinimumSize(QtCore.QSize(95, 20))
        self.hue_Label.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.hue_Label.setFont(font)
        self.hue_Label.setObjectName("hue_Label")
        self.horizontalLayout_2.addWidget(self.hue_Label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hue_slider = QtWidgets.QSlider(self.groupBox_2)
        self.hue_slider.setMinimumSize(QtCore.QSize(250, 20))
        self.hue_slider.setMaximumSize(QtCore.QSize(250, 20))
        self.hue_slider.setMaximum(179)
        self.hue_slider.setOrientation(QtCore.Qt.Horizontal)
        self.hue_slider.setObjectName("hue_slider")
        self.horizontalLayout.addWidget(self.hue_slider)
        self.hue_spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.hue_spinBox.setMinimumSize(QtCore.QSize(28, 20))
        self.hue_spinBox.setMaximumSize(QtCore.QSize(28, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.hue_spinBox.setFont(font)
        self.hue_spinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hue_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.hue_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.hue_spinBox.setMinimum(0)
        self.hue_spinBox.setMaximum(179)
        self.hue_spinBox.setProperty("value", 0)
        self.hue_spinBox.setObjectName("hue_spinBox")
        self.horizontalLayout.addWidget(self.hue_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saturation_label = QtWidgets.QLabel(self.groupBox_2)
        self.saturation_label.setMinimumSize(QtCore.QSize(95, 20))
        self.saturation_label.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.saturation_label.setFont(font)
        self.saturation_label.setObjectName("saturation_label")
        self.horizontalLayout_4.addWidget(self.saturation_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saturation_slider = QtWidgets.QSlider(self.groupBox_2)
        self.saturation_slider.setMinimumSize(QtCore.QSize(250, 20))
        self.saturation_slider.setMaximumSize(QtCore.QSize(250, 20))
        self.saturation_slider.setMaximum(200)
        self.saturation_slider.setSingleStep(1)
        self.saturation_slider.setPageStep(10)
        self.saturation_slider.setProperty("value", 100)
        self.saturation_slider.setOrientation(QtCore.Qt.Horizontal)
        self.saturation_slider.setObjectName("saturation_slider")
        self.horizontalLayout_3.addWidget(self.saturation_slider)
        self.saturation_spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.saturation_spinBox.setMinimumSize(QtCore.QSize(28, 20))
        self.saturation_spinBox.setMaximumSize(QtCore.QSize(28, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.saturation_spinBox.setFont(font)
        self.saturation_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.saturation_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.saturation_spinBox.setMaximum(200)
        self.saturation_spinBox.setProperty("value", 100)
        self.saturation_spinBox.setObjectName("saturation_spinBox")
        self.horizontalLayout_3.addWidget(self.saturation_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.brightness_label = QtWidgets.QLabel(self.groupBox_2)
        self.brightness_label.setMinimumSize(QtCore.QSize(95, 20))
        self.brightness_label.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.brightness_label.setFont(font)
        self.brightness_label.setObjectName("brightness_label")
        self.horizontalLayout_6.addWidget(self.brightness_label)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.brightness_slider = QtWidgets.QSlider(self.groupBox_2)
        self.brightness_slider.setMinimumSize(QtCore.QSize(250, 20))
        self.brightness_slider.setMaximumSize(QtCore.QSize(250, 20))
        self.brightness_slider.setMaximum(150)
        self.brightness_slider.setProperty("value", 100)
        self.brightness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_slider.setObjectName("brightness_slider")
        self.horizontalLayout_5.addWidget(self.brightness_slider)
        self.brightness_spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.brightness_spinBox.setMinimumSize(QtCore.QSize(28, 20))
        self.brightness_spinBox.setMaximumSize(QtCore.QSize(28, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.brightness_spinBox.setFont(font)
        self.brightness_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.brightness_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.brightness_spinBox.setMaximum(150)
        self.brightness_spinBox.setProperty("value", 100)
        self.brightness_spinBox.setObjectName("brightness_spinBox")
        self.horizontalLayout_5.addWidget(self.brightness_spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.triangulation_check_box = QtWidgets.QCheckBox(self.groupBox_2)
        self.triangulation_check_box.setEnabled(True)
        self.triangulation_check_box.setMinimumSize(QtCore.QSize(20, 20))
        self.triangulation_check_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.triangulation_check_box.setFont(font)
        self.triangulation_check_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.triangulation_check_box.setAutoFillBackground(True)
        self.triangulation_check_box.setChecked(True)
        self.triangulation_check_box.setObjectName("triangulation_check_box")
        self.horizontalLayout_12.addWidget(self.triangulation_check_box)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem11 = QtWidgets.QSpacerItem(37, 13, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem11)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setMinimumSize(QtCore.QSize(320, 270))
        self.groupBox.setMaximumSize(QtCore.QSize(320, 270))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.triangulate_options = QtWidgets.QWidget(self.groupBox)
        self.triangulate_options.setEnabled(True)
        self.triangulate_options.setGeometry(QtCore.QRect(10, 20, 300, 240))
        self.triangulate_options.setMinimumSize(QtCore.QSize(300, 240))
        self.triangulate_options.setMaximumSize(QtCore.QSize(300, 240))
        self.triangulate_options.setObjectName("triangulate_options")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.triangulate_options)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.max_points_label = QtWidgets.QLabel(self.triangulate_options)
        self.max_points_label.setMinimumSize(QtCore.QSize(95, 20))
        self.max_points_label.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.max_points_label.setFont(font)
        self.max_points_label.setObjectName("max_points_label")
        self.horizontalLayout_7.addWidget(self.max_points_label)
        spacerItem12 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.line = QtWidgets.QFrame(self.triangulate_options)
        self.line.setMinimumSize(QtCore.QSize(118, 20))
        self.line.setMaximumSize(QtCore.QSize(118, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        spacerItem13 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.max_points_spinBox = QtWidgets.QSpinBox(self.triangulate_options)
        self.max_points_spinBox.setMinimumSize(QtCore.QSize(40, 20))
        self.max_points_spinBox.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.max_points_spinBox.setFont(font)
        self.max_points_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.max_points_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_points_spinBox.setMinimum(20)
        self.max_points_spinBox.setMaximum(10000)
        self.max_points_spinBox.setProperty("value", 2000)
        self.max_points_spinBox.setObjectName("max_points_spinBox")
        self.horizontalLayout_7.addWidget(self.max_points_spinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem14)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.threshold_label = QtWidgets.QLabel(self.triangulate_options)
        self.threshold_label.setMinimumSize(QtCore.QSize(95, 20))
        self.threshold_label.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.threshold_label.setFont(font)
        self.threshold_label.setObjectName("threshold_label")
        self.horizontalLayout_8.addWidget(self.threshold_label)
        spacerItem15 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.line_2 = QtWidgets.QFrame(self.triangulate_options)
        self.line_2.setMinimumSize(QtCore.QSize(118, 20))
        self.line_2.setMaximumSize(QtCore.QSize(118, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        spacerItem16 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.threshold_spinBox = QtWidgets.QDoubleSpinBox(self.triangulate_options)
        self.threshold_spinBox.setMinimumSize(QtCore.QSize(50, 20))
        self.threshold_spinBox.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.threshold_spinBox.setFont(font)
        self.threshold_spinBox.setMinimum(0.01)
        self.threshold_spinBox.setMaximum(1.0)
        self.threshold_spinBox.setSingleStep(0.1)
        self.threshold_spinBox.setProperty("value", 0.33)
        self.threshold_spinBox.setObjectName("threshold_spinBox")
        self.horizontalLayout_8.addWidget(self.threshold_spinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem17 = QtWidgets.QSpacerItem(276, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem17)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scale_factor_label = QtWidgets.QLabel(self.triangulate_options)
        self.scale_factor_label.setMinimumSize(QtCore.QSize(95, 20))
        self.scale_factor_label.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.scale_factor_label.setFont(font)
        self.scale_factor_label.setObjectName("scale_factor_label")
        self.horizontalLayout_9.addWidget(self.scale_factor_label)
        spacerItem18 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem18)
        self.scale_factor_slider = QtWidgets.QSlider(self.triangulate_options)
        self.scale_factor_slider.setEnabled(True)
        self.scale_factor_slider.setMinimumSize(QtCore.QSize(118, 20))
        self.scale_factor_slider.setMaximumSize(QtCore.QSize(118, 20))
        self.scale_factor_slider.setMinimum(1)
        self.scale_factor_slider.setMaximum(100)
        self.scale_factor_slider.setSingleStep(1)
        self.scale_factor_slider.setPageStep(10)
        self.scale_factor_slider.setProperty("value", 10)
        self.scale_factor_slider.setOrientation(QtCore.Qt.Horizontal)
        self.scale_factor_slider.setObjectName("scale_factor_slider")
        self.horizontalLayout_9.addWidget(self.scale_factor_slider)
        spacerItem19 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem19)
        self.scale_factor_spinBox = QtWidgets.QSpinBox(self.triangulate_options)
        self.scale_factor_spinBox.setMinimumSize(QtCore.QSize(40, 20))
        self.scale_factor_spinBox.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.scale_factor_spinBox.setFont(font)
        self.scale_factor_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.scale_factor_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.scale_factor_spinBox.setMinimum(1)
        self.scale_factor_spinBox.setMaximum(100)
        self.scale_factor_spinBox.setProperty("value", 10)
        self.scale_factor_spinBox.setDisplayIntegerBase(10)
        self.scale_factor_spinBox.setObjectName("scale_factor_spinBox")
        self.horizontalLayout_9.addWidget(self.scale_factor_spinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem20 = QtWidgets.QSpacerItem(276, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem20)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.draw_line_checkBox = QtWidgets.QCheckBox(self.triangulate_options)
        self.draw_line_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.draw_line_checkBox.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.draw_line_checkBox.setFont(font)
        self.draw_line_checkBox.setObjectName("draw_line_checkBox")
        self.horizontalLayout_10.addWidget(self.draw_line_checkBox)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem21)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem22 = QtWidgets.QSpacerItem(37, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem22)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.thickness_label = QtWidgets.QLabel(self.triangulate_options)
        self.thickness_label.setMinimumSize(QtCore.QSize(95, 20))
        self.thickness_label.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.thickness_label.setFont(font)
        self.thickness_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.thickness_label.setObjectName("thickness_label")
        self.horizontalLayout_11.addWidget(self.thickness_label)
        spacerItem23 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.thickness_slider = QtWidgets.QSlider(self.triangulate_options)
        self.thickness_slider.setEnabled(False)
        self.thickness_slider.setMinimumSize(QtCore.QSize(118, 20))
        self.thickness_slider.setMaximumSize(QtCore.QSize(118, 20))
        self.thickness_slider.setMinimum(1)
        self.thickness_slider.setMaximum(5)
        self.thickness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.thickness_slider.setObjectName("thickness_slider")
        self.horizontalLayout_11.addWidget(self.thickness_slider)
        spacerItem24 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem24)
        self.thickness_spinBox = QtWidgets.QSpinBox(self.triangulate_options)
        self.thickness_spinBox.setEnabled(False)
        self.thickness_spinBox.setMinimumSize(QtCore.QSize(30, 20))
        self.thickness_spinBox.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.thickness_spinBox.setFont(font)
        self.thickness_spinBox.setMinimum(1)
        self.thickness_spinBox.setMaximum(5)
        self.thickness_spinBox.setObjectName("thickness_spinBox")
        self.horizontalLayout_11.addWidget(self.thickness_spinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.groupBox_2, 1, 4, 3, 2)
        self.apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.apply_button.setMinimumSize(QtCore.QSize(0, 30))
        self.apply_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.apply_button.setFont(font)
        self.apply_button.setObjectName("apply_button")
        self.gridLayout.addWidget(self.apply_button, 5, 4, 1, 2)
        spacerItem25 = QtWidgets.QSpacerItem(20, 349, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem25, 2, 6, 1, 1)
        self.status_message = QtWidgets.QLabel(self.centralwidget)
        self.status_message.setMinimumSize(QtCore.QSize(340, 20))
        self.status_message.setMaximumSize(QtCore.QSize(340, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setItalic(True)
        self.status_message.setFont(font)
        self.status_message.setText("")
        self.status_message.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.status_message.setObjectName("status_message")
        self.gridLayout.addWidget(self.status_message, 4, 4, 1, 2)
        spacerItem26 = QtWidgets.QSpacerItem(20, 278, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem26, 3, 3, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(877, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem27, 6, 2, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(877, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem28, 1, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionNew_Window = QtWidgets.QAction(MainWindow)
        self.actionNew_Window.setObjectName("actionNew_Window")

        self.retranslateUi(MainWindow)
        self.hue_spinBox.valueChanged['int'].connect(self.hue_slider.setValue)
        self.hue_slider.valueChanged['int'].connect(self.hue_spinBox.setValue)
        self.saturation_slider.valueChanged['int'].connect(self.saturation_spinBox.setValue)
        self.saturation_spinBox.valueChanged['int'].connect(self.saturation_slider.setValue)
        self.brightness_spinBox.valueChanged['int'].connect(self.brightness_slider.setValue)
        self.brightness_slider.valueChanged['int'].connect(self.brightness_spinBox.setValue)
        self.scale_factor_slider.valueChanged['int'].connect(self.scale_factor_spinBox.setValue)
        self.scale_factor_spinBox.valueChanged['int'].connect(self.scale_factor_slider.setValue)
        self.triangulation_check_box.toggled['bool'].connect(self.triangulate_options.setEnabled)
        self.thickness_slider.valueChanged['int'].connect(self.thickness_spinBox.setValue)
        self.thickness_spinBox.valueChanged['int'].connect(self.thickness_slider.setValue)
        self.draw_line_checkBox.toggled['bool'].connect(self.thickness_slider.setEnabled)
        self.draw_line_checkBox.toggled['bool'].connect(self.thickness_spinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Delaunay\'s Dream"))
        MainWindow.setStatusTip(_translate("MainWindow", "Delaunay\'s Dream"))
        self.video_player.setStatusTip(_translate("MainWindow", "Video Playback"))
        self.video_slider.setStatusTip(_translate("MainWindow", "Video Seek Bar"))
        self.play_button.setStatusTip(_translate("MainWindow", "Play/Pause Video"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.stop_button.setStatusTip(_translate("MainWindow", "Stop Video"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.frame_viewer.setStatusTip(_translate("MainWindow", "Frame Viewer"))
        self.open_button.setStatusTip(_translate("MainWindow", "New Project"))
        self.open_button.setText(_translate("MainWindow", "New"))
        self.export_button.setStatusTip(_translate("MainWindow", "Export Video"))
        self.export_button.setText(_translate("MainWindow", "Export"))
        self.groupBox_2.setToolTip(_translate("MainWindow", "Delaunay\'s Dream"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Delaunay\'s Dream"))
        self.hue_Label.setStatusTip(_translate("MainWindow", "Hue"))
        self.hue_Label.setText(_translate("MainWindow", "  Hue"))
        self.hue_slider.setStatusTip(_translate("MainWindow", "Adjust Hue (0 - 179)"))
        self.hue_spinBox.setStatusTip(_translate("MainWindow", "Adjust Hue (0 - 179)"))
        self.saturation_label.setStatusTip(_translate("MainWindow", "Saturation"))
        self.saturation_label.setText(_translate("MainWindow", "  Saturation"))
        self.saturation_slider.setStatusTip(_translate("MainWindow", "Adjust Saturation (0 - 200)"))
        self.saturation_spinBox.setStatusTip(_translate("MainWindow", "Adjust Saturation (0 - 200)"))
        self.brightness_label.setStatusTip(_translate("MainWindow", "Brightness"))
        self.brightness_label.setText(_translate("MainWindow", "  Brightness"))
        self.brightness_slider.setStatusTip(_translate("MainWindow", "Adjust Brightness (0 - 150)"))
        self.brightness_spinBox.setStatusTip(_translate("MainWindow", "Adjust Brightness (0 - 150)"))
        self.triangulation_check_box.setStatusTip(_translate("MainWindow", "Triangulate Video"))
        self.triangulation_check_box.setText(_translate("MainWindow", "Triangulate Video"))
        self.groupBox.setStatusTip(_translate("MainWindow", "Triangulate Options"))
        self.groupBox.setTitle(_translate("MainWindow", "Triangulate Options"))
        self.max_points_label.setStatusTip(_translate("MainWindow", "Max Points"))
        self.max_points_label.setText(_translate("MainWindow", "Max Points"))
        self.line.setStatusTip(_translate("MainWindow", "Max Points"))
        self.max_points_spinBox.setStatusTip(_translate("MainWindow", "Adjust number of points used to triangulate (20 - 10000)"))
        self.threshold_label.setStatusTip(_translate("MainWindow", "Threshold"))
        self.threshold_label.setText(_translate("MainWindow", "Threshold"))
        self.line_2.setStatusTip(_translate("MainWindow", "Threshold"))
        self.threshold_spinBox.setStatusTip(_translate("MainWindow", "Adjust Threshold (0.01 - 1.00)"))
        self.scale_factor_label.setStatusTip(_translate("MainWindow", "Scale Factor"))
        self.scale_factor_label.setText(_translate("MainWindow", "Scale Factor"))
        self.scale_factor_slider.setStatusTip(_translate("MainWindow", "Adjust Scale Factor Percentage (1% - 100%)"))
        self.scale_factor_spinBox.setStatusTip(_translate("MainWindow", "Adjust Scale Factor Percentage (1% - 100%)"))
        self.scale_factor_spinBox.setSuffix(_translate("MainWindow", "%"))
        self.draw_line_checkBox.setStatusTip(_translate("MainWindow", "Draw Line"))
        self.draw_line_checkBox.setText(_translate("MainWindow", "Draw Line"))
        self.thickness_label.setStatusTip(_translate("MainWindow", "Thickness"))
        self.thickness_label.setText(_translate("MainWindow", "Thickness"))
        self.thickness_slider.setStatusTip(_translate("MainWindow", "Adjust Line Thickness (1 - 5)"))
        self.thickness_spinBox.setStatusTip(_translate("MainWindow", "Adjust Line Thickness (1 - 5)"))
        self.apply_button.setStatusTip(_translate("MainWindow", "Apply Changes to All Frames"))
        self.apply_button.setText(_translate("MainWindow", "Apply to All Frames"))
        self.status_message.setStatusTip(_translate("MainWindow", "Status Bar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew_Window.setText(_translate("MainWindow", "New Window"))
