# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 781)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("film.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_14.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.video_player = QtWidgets.QLabel(self.centralwidget)
        self.video_player.setMinimumSize(QtCore.QSize(644, 484))
        self.video_player.setStyleSheet("background-color: rgb(239, 239, 239); border : 2px solid rgb(209, 209, 209); min-height: 480; min-width:  640; max-height: 480; max-width:  640;")
        self.video_player.setText("")
        self.video_player.setAlignment(QtCore.Qt.AlignCenter)
        self.video_player.setObjectName("video_player")
        self.verticalLayout_4.addWidget(self.video_player)
        self.video_slider = QtWidgets.QSlider(self.centralwidget)
        self.video_slider.setMaximumSize(QtCore.QSize(644, 16777215))
        self.video_slider.setOrientation(QtCore.Qt.Horizontal)
        self.video_slider.setObjectName("video_slider")
        self.verticalLayout_4.addWidget(self.video_slider)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.play_button.setFont(font)
        self.play_button.setObjectName("play_button")
        self.horizontalLayout_5.addWidget(self.play_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.stop_button.setFont(font)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_5.addWidget(self.stop_button)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem3)
        self.frame_viewer = QtWidgets.QLabel(self.centralwidget)
        self.frame_viewer.setStyleSheet("background-color: rgb(239, 239, 239); border : 2px solid rgb(209, 209, 209); min-height: 100; min-width:  640; max-height: 100; max-width:  640;")
        self.frame_viewer.setText("")
        self.frame_viewer.setObjectName("frame_viewer")
        self.verticalLayout_4.addWidget(self.frame_viewer)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hue_Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.hue_Label.setFont(font)
        self.hue_Label.setObjectName("hue_Label")
        self.verticalLayout_2.addWidget(self.hue_Label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hue_slider = QtWidgets.QSlider(self.centralwidget)
        self.hue_slider.setMaximum(179)
        self.hue_slider.setOrientation(QtCore.Qt.Horizontal)
        self.hue_slider.setObjectName("hue_slider")
        self.horizontalLayout_2.addWidget(self.hue_slider)
        self.hue_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.hue_spinBox.setFont(font)
        self.hue_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.hue_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.hue_spinBox.setMaximum(179)
        self.hue_spinBox.setObjectName("hue_spinBox")
        self.horizontalLayout_2.addWidget(self.hue_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.saturation_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.saturation_label.setFont(font)
        self.saturation_label.setObjectName("saturation_label")
        self.verticalLayout_3.addWidget(self.saturation_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saturation_slider = QtWidgets.QSlider(self.centralwidget)
        self.saturation_slider.setMaximum(200)
        self.saturation_slider.setSingleStep(1)
        self.saturation_slider.setPageStep(10)
        self.saturation_slider.setProperty("value", 100)
        self.saturation_slider.setOrientation(QtCore.Qt.Horizontal)
        self.saturation_slider.setObjectName("saturation_slider")
        self.horizontalLayout_3.addWidget(self.saturation_slider)
        self.saturation_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.saturation_spinBox.setFont(font)
        self.saturation_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.saturation_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.saturation_spinBox.setMaximum(200)
        self.saturation_spinBox.setProperty("value", 100)
        self.saturation_spinBox.setObjectName("saturation_spinBox")
        self.horizontalLayout_3.addWidget(self.saturation_spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.brightness_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.brightness_label.setFont(font)
        self.brightness_label.setObjectName("brightness_label")
        self.verticalLayout_5.addWidget(self.brightness_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.brightness_slider = QtWidgets.QSlider(self.centralwidget)
        self.brightness_slider.setMaximum(150)
        self.brightness_slider.setProperty("value", 100)
        self.brightness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_slider.setObjectName("brightness_slider")
        self.horizontalLayout_4.addWidget(self.brightness_slider)
        self.brightness_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.brightness_spinBox.setFont(font)
        self.brightness_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.brightness_spinBox.setMaximum(150)
        self.brightness_spinBox.setProperty("value", 100)
        self.brightness_spinBox.setObjectName("brightness_spinBox")
        self.horizontalLayout_4.addWidget(self.brightness_spinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12.addLayout(self.verticalLayout_5)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_rate_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.frame_rate_label.setFont(font)
        self.frame_rate_label.setObjectName("frame_rate_label")
        self.verticalLayout.addWidget(self.frame_rate_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_rate_slider = QtWidgets.QSlider(self.centralwidget)
        self.frame_rate_slider.setEnabled(True)
        self.frame_rate_slider.setMinimum(1)
        self.frame_rate_slider.setMaximum(5)
        self.frame_rate_slider.setSingleStep(1)
        self.frame_rate_slider.setPageStep(1)
        self.frame_rate_slider.setProperty("value", 5)
        self.frame_rate_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_rate_slider.setObjectName("frame_rate_slider")
        self.horizontalLayout.addWidget(self.frame_rate_slider)
        self.frame_rate_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.frame_rate_spinBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.frame_rate_spinBox.setFont(font)
        self.frame_rate_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.frame_rate_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.frame_rate_spinBox.setMaximum(100)
        self.frame_rate_spinBox.setObjectName("frame_rate_spinBox")
        self.horizontalLayout.addWidget(self.frame_rate_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem5)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.triangulation_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.triangulation_check_box.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.triangulation_check_box.setFont(font)
        self.triangulation_check_box.setStatusTip("")
        self.triangulation_check_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.triangulation_check_box.setAutoFillBackground(True)
        self.triangulation_check_box.setChecked(True)
        self.triangulation_check_box.setObjectName("triangulation_check_box")
        self.horizontalLayout_15.addWidget(self.triangulation_check_box)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.triangulate_options = QtWidgets.QWidget(self.groupBox)
        self.triangulate_options.setEnabled(True)
        self.triangulate_options.setGeometry(QtCore.QRect(10, 28, 334, 114))
        self.triangulate_options.setObjectName("triangulate_options")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.triangulate_options)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.triangulate_layout = QtWidgets.QVBoxLayout()
        self.triangulate_layout.setObjectName("triangulate_layout")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.max_points_label = QtWidgets.QLabel(self.triangulate_options)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.max_points_label.setFont(font)
        self.max_points_label.setObjectName("max_points_label")
        self.horizontalLayout_7.addWidget(self.max_points_label)
        self.max_points_spinBox = QtWidgets.QSpinBox(self.triangulate_options)
        self.max_points_spinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.max_points_spinBox.setFont(font)
        self.max_points_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.max_points_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_points_spinBox.setMinimum(20)
        self.max_points_spinBox.setMaximum(10000)
        self.max_points_spinBox.setProperty("value", 2000)
        self.max_points_spinBox.setObjectName("max_points_spinBox")
        self.horizontalLayout_7.addWidget(self.max_points_spinBox)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.threshold_label = QtWidgets.QLabel(self.triangulate_options)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.threshold_label.setFont(font)
        self.threshold_label.setObjectName("threshold_label")
        self.horizontalLayout_17.addWidget(self.threshold_label)
        self.threshold_spinBox = QtWidgets.QDoubleSpinBox(self.triangulate_options)
        self.threshold_spinBox.setMinimum(0.01)
        self.threshold_spinBox.setMaximum(1.0)
        self.threshold_spinBox.setSingleStep(0.1)
        self.threshold_spinBox.setProperty("value", 0.33)
        self.threshold_spinBox.setObjectName("threshold_spinBox")
        self.horizontalLayout_17.addWidget(self.threshold_spinBox)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.triangulate_layout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scale_factor_label = QtWidgets.QLabel(self.triangulate_options)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.scale_factor_label.setFont(font)
        self.scale_factor_label.setObjectName("scale_factor_label")
        self.horizontalLayout_8.addWidget(self.scale_factor_label)
        self.scale_factor_slider = QtWidgets.QSlider(self.triangulate_options)
        self.scale_factor_slider.setEnabled(True)
        self.scale_factor_slider.setMinimum(1)
        self.scale_factor_slider.setMaximum(100)
        self.scale_factor_slider.setSingleStep(1)
        self.scale_factor_slider.setPageStep(10)
        self.scale_factor_slider.setProperty("value", 10)
        self.scale_factor_slider.setOrientation(QtCore.Qt.Horizontal)
        self.scale_factor_slider.setObjectName("scale_factor_slider")
        self.horizontalLayout_8.addWidget(self.scale_factor_slider)
        self.scale_factor_spinBox = QtWidgets.QSpinBox(self.triangulate_options)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.scale_factor_spinBox.setFont(font)
        self.scale_factor_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.scale_factor_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.scale_factor_spinBox.setMinimum(1)
        self.scale_factor_spinBox.setMaximum(100)
        self.scale_factor_spinBox.setProperty("value", 10)
        self.scale_factor_spinBox.setDisplayIntegerBase(10)
        self.scale_factor_spinBox.setObjectName("scale_factor_spinBox")
        self.horizontalLayout_8.addWidget(self.scale_factor_spinBox)
        self.triangulate_layout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addLayout(self.triangulate_layout)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.draw_line_checkBox = QtWidgets.QCheckBox(self.triangulate_options)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.draw_line_checkBox.setFont(font)
        self.draw_line_checkBox.setObjectName("draw_line_checkBox")
        self.horizontalLayout_20.addWidget(self.draw_line_checkBox)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.thickness_label = QtWidgets.QLabel(self.triangulate_options)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.thickness_label.setFont(font)
        self.thickness_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.thickness_label.setObjectName("thickness_label")
        self.horizontalLayout_19.addWidget(self.thickness_label)
        self.thickness_slider = QtWidgets.QSlider(self.triangulate_options)
        self.thickness_slider.setEnabled(False)
        self.thickness_slider.setMinimum(1)
        self.thickness_slider.setMaximum(5)
        self.thickness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.thickness_slider.setObjectName("thickness_slider")
        self.horizontalLayout_19.addWidget(self.thickness_slider)
        self.thickness_spinBox = QtWidgets.QSpinBox(self.triangulate_options)
        self.thickness_spinBox.setEnabled(False)
        self.thickness_spinBox.setMinimum(1)
        self.thickness_spinBox.setMaximum(5)
        self.thickness_spinBox.setObjectName("thickness_spinBox")
        self.horizontalLayout_19.addWidget(self.thickness_spinBox)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.status_message = QtWidgets.QLabel(self.centralwidget)
        self.status_message.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setItalic(True)
        self.status_message.setFont(font)
        self.status_message.setText("")
        self.status_message.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.status_message.setObjectName("status_message")
        self.verticalLayout_6.addWidget(self.status_message)
        self.apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.apply_button.setObjectName("apply_button")
        self.verticalLayout_6.addWidget(self.apply_button)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.open_button.setFont(font)
        self.open_button.setObjectName("open_button")
        self.horizontalLayout_13.addWidget(self.open_button)
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.export_button.setFont(font)
        self.export_button.setObjectName("export_button")
        self.horizontalLayout_13.addWidget(self.export_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.verticalLayout_11.addLayout(self.verticalLayout_6)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.horizontalLayout_14.addLayout(self.verticalLayout_12)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionNew_Window = QtWidgets.QAction(MainWindow)
        self.actionNew_Window.setObjectName("actionNew_Window")

        self.retranslateUi(MainWindow)
        self.hue_spinBox.valueChanged['int'].connect(self.hue_slider.setValue)
        self.hue_slider.valueChanged['int'].connect(self.hue_spinBox.setValue)
        self.saturation_slider.valueChanged['int'].connect(self.saturation_spinBox.setValue)
        self.saturation_spinBox.valueChanged['int'].connect(self.saturation_slider.setValue)
        self.brightness_spinBox.valueChanged['int'].connect(self.brightness_slider.setValue)
        self.brightness_slider.valueChanged['int'].connect(self.brightness_spinBox.setValue)
        self.scale_factor_slider.valueChanged['int'].connect(self.scale_factor_spinBox.setValue)
        self.scale_factor_spinBox.valueChanged['int'].connect(self.scale_factor_slider.setValue)
        self.frame_rate_spinBox.valueChanged['int'].connect(self.frame_rate_slider.setValue)
        self.frame_rate_slider.valueChanged['int'].connect(self.frame_rate_spinBox.setValue)
        self.triangulation_check_box.toggled['bool'].connect(self.triangulate_options.setEnabled)
        self.thickness_slider.valueChanged['int'].connect(self.thickness_spinBox.setValue)
        self.thickness_spinBox.valueChanged['int'].connect(self.thickness_slider.setValue)
        self.draw_line_checkBox.toggled['bool'].connect(self.thickness_slider.setEnabled)
        self.draw_line_checkBox.toggled['bool'].connect(self.thickness_spinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Delaunay\'s Dream"))
        MainWindow.setStatusTip(_translate("MainWindow", "Delaunay\'s Dream"))
        self.play_button.setStatusTip(_translate("MainWindow", "Open File"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.stop_button.setStatusTip(_translate("MainWindow", "Save As..."))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.hue_Label.setText(_translate("MainWindow", "Hue"))
        self.hue_slider.setStatusTip(_translate("MainWindow", "Adjust Hue"))
        self.hue_spinBox.setStatusTip(_translate("MainWindow", "Adjust Hue"))
        self.saturation_label.setText(_translate("MainWindow", "Saturation"))
        self.saturation_slider.setStatusTip(_translate("MainWindow", "Adjust Saturation"))
        self.saturation_spinBox.setStatusTip(_translate("MainWindow", "Adjust Saturation"))
        self.brightness_label.setText(_translate("MainWindow", "Brightness"))
        self.brightness_slider.setStatusTip(_translate("MainWindow", "Adjust Brightness"))
        self.brightness_spinBox.setStatusTip(_translate("MainWindow", "Adjust Brightness"))
        self.frame_rate_label.setText(_translate("MainWindow", "Frame Rate"))
        self.frame_rate_slider.setStatusTip(_translate("MainWindow", "Adjust Frame Rate"))
        self.frame_rate_spinBox.setStatusTip(_translate("MainWindow", "Adjust Frame Rate"))
        self.triangulation_check_box.setText(_translate("MainWindow", "Triangulate Video"))
        self.groupBox.setTitle(_translate("MainWindow", "Triangulate Options"))
        self.max_points_label.setText(_translate("MainWindow", "Max Points"))
        self.max_points_spinBox.setStatusTip(_translate("MainWindow", "Adjust number of points used to triangulate"))
        self.threshold_label.setText(_translate("MainWindow", "Threshold"))
        self.scale_factor_label.setText(_translate("MainWindow", "Scale Factor"))
        self.scale_factor_slider.setStatusTip(_translate("MainWindow", "Adjust Frame Rate"))
        self.scale_factor_spinBox.setStatusTip(_translate("MainWindow", "Adjust Hue"))
        self.scale_factor_spinBox.setSuffix(_translate("MainWindow", "%"))
        self.draw_line_checkBox.setText(_translate("MainWindow", "Draw Line"))
        self.thickness_label.setText(_translate("MainWindow", "Thickness"))
        self.apply_button.setText(_translate("MainWindow", "Apply to All Frames"))
        self.open_button.setStatusTip(_translate("MainWindow", "Open File"))
        self.open_button.setText(_translate("MainWindow", "Open"))
        self.export_button.setStatusTip(_translate("MainWindow", "Save As..."))
        self.export_button.setText(_translate("MainWindow", "Export"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew_Window.setText(_translate("MainWindow", "New Window"))
